#!/bin/bash
import os
import py_compile

pyfile = os.getenv('PYFILE')

if pyfile:
    output_filename = pyfile + 'c'

    py_compile.compile(pyfile, cfile=output_filename)
else:
    print("Error: PYFILE environment variable not set.")

