#!/bin/bash
import os
import py_compil
pyfile = os.getenv('PYFILE'
if pyfile:
    output_filename = pyfile + 'c'
    py_compile.compile(pyfile, cfile=output_filename)
    print(f"Compiled {pyfile} to {output_filename}")
else:
    print("Error: PYFILE environment variable not set.")

